name: Publish Python distributions to PyPI and TestPyPI
on: push

jobs:
  build-n-publish:
    name: Build and publish Python distributions to PyPI and TestPyPI
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['2.7', '3.x']

    steps:
    - uses: actions/checkout@master

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install pep517
      run: >-
        python -m
        pip install
        pep517
        --user

    - name: Build a source tarball
      if: ${{ matrix.python-version }} == '3.x'
      run: >-
        python -m
        pep517.build
        --source
        .

    - name: Build a binary wheel
      run: >-
        python -m
        pep517.build
        --binary
        --out-dir dist/
        .

    - name: Lint with flake8
      run: |
        python -m pip install flake8 --user
        python -m flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        python -m flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Publish distribution to Test PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.pypi_test_password }}
        repository_url: https://test.pypi.org/legacy/

    - name: Publish distribution to PyPI
      if: startsWith(github.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.pypi_password }}
